version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:12.6
    restart: unless-stopped
    ports:
    - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"