version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:12.6
    restart: unless-stopped
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"

  propaganda:
    container_name: propaganda

    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "POSTGRES_URL=postgres"
      # - "POSTGRES_PORT=5432"
      - "CLIENT_ID=${CLIENT_ID}"
      - "CLIENT_SECRET=${CLIENT_SECRET}"
      - "APP_ID=${APP_ID}"
      - "INSTALLATION_ID=${INSTALLATION_ID}"
      - "ORGANISATION_NAME=${ORGANISATION_NAME}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"