= 3 Wöchiges Uni Projekt mit @nino-salih @Cskorpion und @balam101

= Starten des Systems

Das Projekt benutzt `docker` sowie `docker-compose` beides sollte installiert sein.

Der Gradle Task `build` oder `bootJar` muss mindestens einmal ausgeführt werden.

Es ist wichtig das entweder eine **.env** file geschrieben wird um das Projekt zu konfigurieren oder die **docker-compose.yml** angepasst wird:
```yml
     environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "POSTGRES_URL=postgres"
      - "POSTGRES_PORT=5432"
      - "CLIENT_ID=${CLIENT_ID}"
      - "CLIENT_SECRET=${CLIENT_SECRET}"
      - "APP_ID=${APP_ID}"
      - "INSTALLATION_ID=${INSTALLATION_ID}"
      - "ORGANISATION_NAME=${ORGANISATION_NAME}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
```

Zur Festlegung der systeminternen Rollen wird eine .yml Datei verwendet
```yml
tutoren:
  - GitHubName
organisator:
  - GitHubName
```
[IMPORTANT]
In der Angegebenen Github Organisation muss man ein Mitglied sein sonst bekommt man die `ROLE_BESUCHER` wenn man sich anmeldet. Diese Rolle kann auf keine Seite zugreifen.


Diese kann in Docker geladen werden. Standartmäßig liegt die Datei unter /data/users.yml
```yml
  propaganda:
    volumes:
    - "/path/to/your/users.yml":"/data/users.yml"
```
[NOTE]
Die Systemvariable `ROLE_PATH` kann auch überschrieben werden wenn ein anderer interne Pfad gewünscht ist

Wenn alle vorigen Schritte ausgefuehrt wurden kann das Projekt einfach mit `docker-compose up -d --build` gestartet werden
